### ISSUE TITLE
 Totaljava.io.IOException: File already exists. This may lead to undesired behavior.

### ISSUE THREAD

**Issue by ishandutta2007** [jlooper/practicebuddy#1]
As we discussed I guess it's not tested for andoid yet, do keep tract of this when you do. The repo is breaking on android.

Steps to repro:
1. `git clone https://github.com/jlooper/practicebuddy.git
`

2. `cp google-services.json /Users/ishandutta2007/Documents/Projects/practicebuddy/app/App_Resources/Android/
`
3. Replace everywhere practicebuddy-4d466 with my firebase instance name(only place found was in main.ts `storageBucket: 'gs://practicebuddy-4d466.appspot.com'`)

4.  `tns run android  | while IFS= read -r line; do printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$line"; done `

> [2017-06-03 08:30:43] Running full build
> [2017-06-03 08:30:46] finished with reading lines with js files
> [2017-06-03 08:30:55] Warning: there already is an extend called com.tns.NativeScriptActivity.
> [2017-06-03 08:30:55] Warning: there already is an extend called com.tns.FragmentClass.
> Exception in thread "main" 
> [2017-06-03 08:31:03] :asbg:generateBindings FAILED
> [2017-06-03 08:31:03] 
> [2017-06-03 08:31:03] BUILD FAILED
> [2017-06-03 08:31:03] 
> [2017-06-03 08:31:03] Totaljava.io.IOException: File already exists. This may lead to undesired behavior.
> Please change the name of one of the extended classes.
> /Users/ishandutta2007/Documents/Projects/practicebuddy/platforms/android/src/main/java/com/tns/gen/android/content/BroadcastReceiver_frnal_ts_helpers_l58_c38__BroadcastReceiver.java
>         at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:59)
>         at org.nativescript.staticbindinggenerator.Main.main(Main.java:15)
> 
> FAILURE: Build failed with an exception.
>

**Comment by jlooper** [comment]
I've recently updated to 3.0 so we can test again
